#!/usr/bin/env bash

# This is an attemt to be able to run a script in docker as a specific user
# and still be able to use sudo inside the script.
#
# There must be a much better way :-(
#
# Create a lot of users with uids that hopefully match the uid used
# TBD: What if Jenkins uses a system uid
for uid in {1000..1010}
do
    username="user$uid"
    adduser --no-create-home --disabled-password --home / --uid $uid --gecos $username $username
done

# Let any user be able to run any command with sudo
echo "ALL ALL=(ALL:ALL) NOPASSWD: ALL" > /etc/sudoers.d/sudoers-all
chmod 0440 /etc/sudoers.d/sudoers-all
